# Generated by Django 3.2.8 on 2021-11-27 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='motor',
            fields=[
                ('plat_mtr', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nama_mtr', models.CharField(max_length=225)),
                ('merk_mtr', models.CharField(max_length=225)),
                ('foto_mtr', models.ImageField(blank=True, upload_to='static/motor/motor-img')),
                ('kategori_mtr', models.CharField(choices=[('Matic', 'Matic'), ('Manual', 'Manual'), ('Kopling', 'Kopling')], max_length=225)),
                ('warna_mtr', models.CharField(max_length=225)),
                ('tahun_mtr', models.IntegerField()),
                ('harga_mtr', models.IntegerField()),
                ('status_mtr', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Booked', 'Telah Dibooking')], max_length=225)),
                ('tentang_mtr', models.TextField(max_length=255)),
                ('tanggal_db_mtr', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
