# Generated by Django 3.2.8 on 2021-12-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_alter_motor_tentang_mtr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motor',
            old_name='tanggal_db_mtr',
            new_name='tgl_db_mtr',
        ),
    ]
