# Generated by Django 3.2.8 on 2021-11-27 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobil',
            fields=[
                ('plat_mbl', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nama_mbl', models.CharField(max_length=225)),
                ('merk_mbl', models.CharField(max_length=225)),
                ('foto_mbl', models.ImageField(blank=True, upload_to='static/mobil/mobil-img')),
                ('kategori_mbl', models.CharField(choices=[('Matic', 'Matic'), ('Manual', 'Manual'), ('Hybrid', 'Hybrid')], max_length=225)),
                ('warna_mbl', models.CharField(max_length=225)),
                ('tahun_mbl', models.IntegerField()),
                ('harga_mbl', models.IntegerField()),
                ('status_mbl', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Booked', 'Telah Dibooking')], max_length=225)),
                ('tentang_mbl', models.TextField(max_length=255)),
                ('tgl_db_mbl', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
