# Generated by Django 3.2.8 on 2021-11-27 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='foto_mbl',
            field=models.ImageField(blank=True, upload_to='static/mobil/mobil-img', verbose_name='Foto Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='harga_mbl',
            field=models.IntegerField(verbose_name='Harga Sewa Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='kategori_mbl',
            field=models.CharField(choices=[('Matic', 'Matic'), ('Manual', 'Manual'), ('Hybrid', 'Hybrid')], max_length=225, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='merk_mbl',
            field=models.CharField(max_length=225, verbose_name='Merk'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='nama_mbl',
            field=models.CharField(max_length=225, verbose_name='Nama Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='plat_mbl',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Nomor Plat Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='status_mbl',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Booked', 'Telah Dibooking')], default='Tersedia', max_length=225, verbose_name='Status Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='tahun_mbl',
            field=models.IntegerField(verbose_name='Tahun Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='tentang_mbl',
            field=models.TextField(max_length=500, verbose_name='Deskripsi Mobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='tgl_db_mbl',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Database Dibuat'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='warna_mbl',
            field=models.CharField(max_length=225, verbose_name='Warna Mobil'),
        ),
    ]
