# Generated by Django 3.2.8 on 2021-11-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0002_auto_20211127_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='tentang_mbl',
            field=models.TextField(verbose_name='Deskripsi Mobil'),
        ),
    ]
