# Generated by Django 3.2.8 on 2021-12-04 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobil', '0003_alter_mobil_tentang_mbl'),
        ('motor', '0003_alter_motor_tentang_mtr'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_booking_mtr', models.DateField(null=True, verbose_name='Tanggal Motor Disewa')),
                ('waktu_booking_mtr', models.IntegerField(default=1, verbose_name='Lama Sewa Motor /hari')),
                ('tgl_kembali_mtr', models.DateField(null=True, verbose_name='Tanggal Motor Kembali')),
                ('tgl_reservasi_mtr', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Tanggal Reservasi')),
                ('denda_mtr', models.IntegerField(default=0, verbose_name='Denda Sewa Motor')),
                ('total_sewa_mtr', models.IntegerField(default=0, verbose_name='Total Harga Sewa Motor')),
                ('status_sewa_mtr', models.CharField(choices=[('Dipesan', 'Dipesan'), ('Dibayar', 'Dibayar'), ('Dikembalikan', 'Dikembalikan')], default='Dipesan', max_length=500, verbose_name='Status Sewa Motor')),
                ('id_motor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='motor.motor')),
                ('id_penyewa_mtr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bookMobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_booking_mbl', models.DateField(null=True, verbose_name='Tanggal Mobil Disewa')),
                ('waktu_booking_mbl', models.IntegerField(default=1, verbose_name='Lama Sewa Mobil /hari')),
                ('tgl_kembali_mbl', models.DateField(null=True, verbose_name='Tanggal Mobil Kembali')),
                ('tgl_reservasi_mbl', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Tanggal Reservasi')),
                ('denda_mbl', models.IntegerField(default=0, verbose_name='Denda Sewa Mobil')),
                ('total_sewa_mbl', models.IntegerField(default=0, verbose_name='Total Harga Sewa Mobil')),
                ('status_sewa_mbl', models.CharField(choices=[('Dipesan', 'Dipesan'), ('Dibayar', 'Dibayar'), ('Dikembalikan', 'Dikembalikan')], default='Dipesan', max_length=500, verbose_name='Status Sewa Mobil')),
                ('id_mobil', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mobil.mobil')),
                ('id_penyewa_mbl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
