# Generated by Django 3.2.8 on 2021-12-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmobil',
            name='no_alternatif_mbl',
            field=models.CharField(max_length=25, null=True, verbose_name='No HP Lainnya (opsional)'),
        ),
        migrations.AddField(
            model_name='bookmotor',
            name='no_alternatif_mtr',
            field=models.CharField(max_length=25, null=True, verbose_name='No HP Lainnya (opsional)'),
        ),
    ]
