# Generated by Django 3.2.8 on 2021-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20211204_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmobil',
            name='atas_nama_mbl',
            field=models.CharField(max_length=250, null=True, verbose_name='Atas Nama Rekening Bank'),
        ),
        migrations.AddField(
            model_name='bookmobil',
            name='nama_bank_mbl',
            field=models.CharField(max_length=150, null=True, verbose_name='Nama Bank yg digunakan'),
        ),
        migrations.AddField(
            model_name='bookmobil',
            name='note_mbl',
            field=models.TextField(null=True, verbose_name='Note Pesanan'),
        ),
        migrations.AddField(
            model_name='bookmotor',
            name='atas_nama_mtr',
            field=models.CharField(max_length=250, null=True, verbose_name='Atas Nama Rekening Bank'),
        ),
        migrations.AddField(
            model_name='bookmotor',
            name='nama_bank_mtr',
            field=models.CharField(max_length=150, null=True, verbose_name='Nama Bank yg digunakan'),
        ),
        migrations.AddField(
            model_name='bookmotor',
            name='note_mtr',
            field=models.TextField(null=True, verbose_name='Note Pesanan'),
        ),
    ]
