# Generated by Django 3.2.8 on 2021-12-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20211206_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmotor',
            name='total_sewa_mtr',
            field=models.IntegerField(default=1, verbose_name='Total Harga Sewa Motor'),
        ),
    ]
