# Generated by Django 3.2.8 on 2021-12-27 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookmotor_total_sewa_mtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmotor',
            name='tgl_kembali_mtr',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 8, 2, 40, 981899, tzinfo=utc), null=True, verbose_name='Tanggal Motor Kembali'),
        ),
    ]
