# Generated by Django 3.2.8 on 2021-12-27 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookmotor_tgl_kembali_mtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmotor',
            name='tgl_kembali_mtr',
            field=models.DateField(default=datetime.datetime(2021, 12, 27, 8, 8, 47, 572561, tzinfo=utc), null=True, verbose_name='Tanggal Motor Kembali'),
        ),
    ]
