# Generated by Django 3.2.8 on 2021-12-27 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_bookmotor_tgl_kembali_mtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmotor',
            name='tgl_kembali_mtr',
            field=models.DateField(default=datetime.date(2021, 12, 27), null=True, verbose_name='Tanggal Motor Kembali'),
        ),
    ]
