# Generated by Django 3.2.8 on 2021-12-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_bookmotor_tgl_kembali_mtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmotor',
            name='tgl_kembali_mtr',
            field=models.DateField(null=True, verbose_name='Tanggal Motor Kembali'),
        ),
    ]
