# Generated by Django 3.2.8 on 2021-11-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newakun',
            name='nama',
            field=models.CharField(max_length=70, verbose_name='nama'),
        ),
        migrations.AlterField(
            model_name='newakun',
            name='no_hp',
            field=models.CharField(max_length=15, unique=True, verbose_name='nomor handphone'),
        ),
    ]
