# Generated by Django 3.2.8 on 2021-12-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_auto_20211118_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newakun',
            name='no_hp',
            field=models.CharField(max_length=15, verbose_name='nomor handphone'),
        ),
    ]
